### ISSUE TITLE
直播源API的auth算法有变吗？

### ISSUE THREAD

**Issue by 452MJ** [littleMeng/video-live#2]
直播源API的auth算法有变吗

**Comment by littleMeng** [comment]
是的。
通过反编译apk，发现加密算法藏在so库里面。模仿so的接口调用，能够成功load so库，但是接口调用失败，就没有继续研究。

**Comment by littleMeng** [comment]
https://github.com/soimort/you-get/blob/0984190f93bd0b5c55748c41ca657d1ba6bf5a6b/src/you_get/extractors/douyutv.py
有更新后的斗鱼直播源API的auth算法

**Comment by 452MJ** [comment]
谢谢。
