### ISSUE TITLE
关于直播源地址抓取

### ISSUE THREAD

**Issue by 068089dy** [littleMeng/video-live#4]
我看到你在“修改斗鱼直播源请求加密算法 ”时，在 app/src/main/java/com/example/meng/videolive/utils/BuildUrl.java 中改变了这行代码：
```
return "http://www.douyu.com/lapi/live/getPlay/" + roomId;
return "http://coapi.douyucdn.cn/lapi/live/thirdPart/getPlay/" + roomId + "?rate=0";
```
请问"http://coapi.douyucdn.cn/lapi/live/thirdPart/getPlay/" + roomId + "?rate=0"这个地址你是怎么发现的，我在linux下用浏览器get请求这个地址的响应是{"error":1001,"data":[]}，但是在手机app上用java代码请求却能成功，是操作系统的原因吗？并且我在抓包时只发现了"http://www.douyu.com/lapi/live/getPlay/" + roomId这个地址。

**Comment by littleMeng** [comment]
还有在header塞了几个字段进去，完整看commit日志。

**Comment by 068089dy** [comment]
好的，谢谢

**Comment by 068089dy** [comment]
@littleMeng 好的，谢谢，还有你是怎么知道get这个地址能返回直播源的，我在访问斗鱼网站时没有发现有这个请求啊。
