### ISSUE TITLE
how to compile on linux ssh?

### ISSUE THREAD

**Issue by kmahyyg** [littleMeng/video-live#5]
newbie，使用debian，仅安装了ndk，如何操作？需要指定哪些环境变量？or else you can upload a latest release with pre-compiled version

**Comment by 068089dy** [comment]
l can not read your question, you still use  English! We have translation software.

**Comment by kmahyyg** [comment]
怎么在debian下使用ndk-build编译？只有cli，新手。需要设置哪些环境变量？

**Comment by 068089dy** [comment]
sorry,l can not help you,l used android-studio.
